language: node_js
dist: xenial
node_js:
  - "10"

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - /^@test\/.*/

jobs:
  include:
    - name: "Test"
      script: |
        echo "Testing..."

    - name: "Build & Deploy"
      script: |
        echo "Building and Deploying"

deploy:
  - provider: script
    script:
      - echo "Deploying..."
    skip_cleanup: true
    on:
      tags: true
      branch: master
